# Generated by Django 4.2.7 on 2023-11-06 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binarytree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryTreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('node_id', models.PositiveIntegerField(unique=True)),
                ('left_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_child', to='binarytree.binarytreenode')),
                ('right_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_child', to='binarytree.binarytreenode')),
            ],
        ),
        migrations.DeleteModel(
            name='LeftNode',
        ),
        migrations.DeleteModel(
            name='RightNode',
        ),
    ]
